### ISSUE TITLE
1.0.8.0和1.0.8.1均报错

### ISSUE THREAD

**Issue by david12-t** [PRaichu/xxqg#47]
win 10操作系统，错误信息如下，似乎是找不到视频控件
Traceback (most recent call last):
  File "xuexi.py", line 136, in <module>
  File "xuexi.py", line 59, in run
  File "operation\watch_video.py", line 27, in watch_video
  File "selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
  File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div/div/section/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div[1]/div[2]/div/div[1]/div[1]/div/video"}
  (Session info: chrome=92.0.4515.159)

**Comment by PRaichu** [comment]
> win 10操作系统，错误信息如下，似乎是找不到视频控件
> Traceback (most recent call last):
> File "xuexi.py", line 136, in
> File "xuexi.py", line 59, in run
> File "operation\watch_video.py", line 27, in watch_video
> File "selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
> File "selenium\webdriver\remote\webdriver.py", line 976, in find_element
> File "selenium\webdriver\remote\webdriver.py", line 321, in execute
> File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div/div/section/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div[1]/div[2]/div/div[1]/div[1]/div/video"}
> (Session info: chrome=92.0.4515.159)

感谢反馈，我会尽快排查问题，近日会发布更新！

**Comment by PRaichu** [comment]
已发布1.0.8.2修复更新，欢迎下载使用

**Comment by waterun** [comment]
xpath确实不太可靠，网页没准啥时候就改一下结构，用类名和tag名相对不会经常变

**Comment by PRaichu** [comment]
> xpath确实不太可靠，网页没准啥时候就改一下结构，用类名和tag名相对不会经常变

是的，项目更新过程中已经陆陆续续替换了大部分xpath了，后续更新也会主要使用id，class，tag去做匹配，尽量避免使用xpath

**Comment by RouJiANG-14** [comment]
> 已发布1.0.8.2修复更新，欢迎下载使用

已更新，目前没发现什么问题，谢谢老铁！

**Comment by david12-t** [comment]
> 已发布1.0.8.2修复更新，欢迎下载使用

感谢及时更新！
