### ISSUE TITLE
不解

### ISSUE THREAD

**Issue by Oliver-F1** [PRaichu/xxqg#52]
Traceback (most recent call last):
  File "xuexi.py", line 136, in <module>
  File "xuexi.py", line 48, in run
  File "userOperation\check.py", line 67, in check_task
IndexError: list index out of range

--> 程序异常，请尝试重启脚本
--> 当前版本:1.0.9.0

**Comment by PRaichu** [comment]
> Traceback (most recent call last):
> File "xuexi.py", line 136, in
> File "xuexi.py", line 48, in run
> File "userOperation\check.py", line 67, in check_task
> IndexError: list index out of range
> 
> --> 程序异常，请尝试重启脚本
> --> 当前版本:1.0.9.0

感谢反馈，重启运行试试看，我这边测试是正常的，如果多次运行依然报错，请详细描述复现方法，并带上报错时浏览器的截图，方便排查问题，谢谢！

**Comment by Oliver-F1** [comment]
重启第三遍后，又不报错了，可以正常运行了，就很神奇
