### ISSUE TITLE
累计积分和总积分，反了

### ISSUE THREAD

**Issue by jjkk52** [PRaichu/xxqg#64]
![image](https://user-images.githubusercontent.com/69285860/149476470-f4f41bb3-4673-4320-badb-b9334bc829b9.png)

**Comment by PRaichu** [comment]
@jjkk52 感谢反馈，这个bug是之前学习强国官方改了页面造成的，但是不影响程序运行，这个问题会在下次程序更新的时候修复

**Comment by PRaichu** [comment]
@jjkk52 该问题已修复，请下载最新版使用！
https://github.com/PRaichu/xxqg/releases/tag/1.0.9.1
