### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by lcqadmin** [PRaichu/xxqg#8]
没有exe文件

**Comment by PRaichu** [comment]
> 没有exe文件

大概率是杀毒软件把exe删掉了，把杀毒软件关掉试试，或者把软件加白名单

**Comment by lcqadmin** [comment]
> > 没有exe文件
> 
> 大概率是杀毒软件把exe删掉了，把杀毒软件关掉试试，或者把软件加白名单

![3`DIS%H (18X1~3}UB~9_OC](https://user-images.githubusercontent.com/74635842/107606560-6cf48300-6c71-11eb-9cbb-b0b39305dc52.png)
没有exe文件

**Comment by PRaichu** [comment]
去Release下载，或者点此[ Release ](https://github.com/PRaichu/xxqg/releases)下载

**Comment by lcqadmin** [comment]
> > 没有exe文件
> 
> 大概率是杀毒软件把exe删掉了，把杀毒软件关掉试试，或者把软件加白名单

没有杀掉

**Comment by lcqadmin** [comment]
> > 没有exe文件
> 
> 大概率是杀毒软件把exe删掉了，把杀毒软件关掉试试，或者把软可以

**Comment by lcqadmin** [comment]
> > 没有exe文件
> 
> 大概率是杀毒软件把exe删掉了，把杀毒软件关掉试试，或者把软件加白名单

可以了  谢谢作者！
